[Window]
enable=true
width=1024
height=576

[Graphics]
enable=true

[GPU]
defaultVertexBufferSize=16777216
defaultVertexBufferSpanCapacity=64
# defaultQuadBufferSize=256
defaultQuadBufferSize=1024
# batchesCapacity=4096
# quadQueueSize=4096
batchesCapacity=8192
quadQueueSize=8192

[Lua]
initModule=init.lua

[Physics]
gravity=9.81
